cc_binary(
    name = "1a",
    srcs = ["1a.cc"],
    deps = [
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/types:optional",
    ]
)

cc_binary(
    name = "1b",
    srcs = ["1b.cc"],
    deps = [
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/types:optional",
    ]
)
